language: php
services: docker
php:
    - '7.2'
before_install:
  - pip install --user awscli
  - curl -o $HOME/.local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - chmod +x $HOME/.local/bin/ecs-cli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - docker build -t $DOCKER_REPO:${TRAVIS_COMMIT::8} -f docker/app/Dockerfile .
script:
  - echo "Tests run here!"
after_success:
  - eval $(aws ecr get-login --region us-east-1 --no-include-email)
  - docker push $DOCKER_REPO:${TRAVIS_COMMIT::8}
  - ecs-cli compose --project-name $PROJECT_NAME --cluster-config $CLUSTER_NAME service up
