version: '2'

services:
  web:
    image: 994642778742.dkr.ecr.us-east-1.amazonaws.com/dallasphpbot/nginx:latest
    volumes_from:
      - app
    ports:
      - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-group: dallasphpbot
        awslogs-region: us-east-1
        awslogs-stream-prefix: dallasphpbot
  fpm:
    image: php:7.2-fpm
    volumes_from:
      - app
    ports:
      - 9000:9000
    environment:
      - SLACK_TOKEN
  app:
    image: ${DOCKER_REPO}:${IMAGE_TAG}
